import React from 'react';
import { ChefHat, Calendar, ShoppingCart, Leaf, Zap, DollarSign } from 'lucide-react';

interface Feature {
  id: string;
  icon: React.ReactNode;
  title: string;
  description: string;
  benefits: string[];
  gradient: string;
}

const features: Feature[] = [
  {
    id: 'ai-recipes',
    icon: <ChefHat className="w-8 h-8" />,
    title: 'AI-Powered Recipes',
    description: 'Discover personalized recipes generated by advanced AI technology tailored to your preferences and dietary needs.',
    benefits: ['Unlimited recipe variations', 'Nutrition tracking', 'Cooking instructions'],
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'meal-planning',
    icon: <Calendar className="w-8 h-8" />,
    title: 'Smart Meal Planning',
    description: 'Automatically generate weekly meal plans that align with your goals, preferences, and available ingredients.',
    benefits: ['Weekly scheduling', 'Balanced nutrition', 'Flexible adjustments'],
    gradient: 'from-blue-500/20 to-cyan-500/20',
  },
  {
    id: 'shopping-lists',
    icon: <ShoppingCart className="w-8 h-8" />,
    title: 'Auto-Generated Shopping Lists',
    description: 'Get organized shopping lists automatically created from your meal plans with quantities and store sections.',
    benefits: ['Smart categorization', 'Price comparison', 'Inventory tracking'],
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 'dietary-preferences',
    icon: <Leaf className="w-8 h-8" />,
    title: 'Dietary Preferences',
    description: 'Support for multiple dietary restrictions and preferences including vegan, keto, gluten-free, and more.',
    benefits: ['Multiple diet types', 'Allergen filtering', 'Custom restrictions'],
    gradient: 'from-green-600/20 to-lime-500/20',
  },
  {
    id: 'time-saving',
    icon: <Zap className="w-8 h-8" />,
    title: 'Time Saving',
    description: 'Reduce meal planning and cooking time by up to 80% with automated suggestions and quick recipes.',
    benefits: ['Quick recipes', 'Batch cooking tips', 'Prep time estimates'],
    gradient: 'from-yellow-500/20 to-orange-500/20',
  },
  {
    id: 'cost-reduction',
    icon: <DollarSign className="w-8 h-8" />,
    title: 'Cost Reduction',
    description: 'Minimize food waste and optimize your budget with intelligent ingredient suggestions and price tracking.',
    benefits: ['Budget optimization', 'Waste reduction', 'Bulk buying tips'],
    gradient: 'from-purple-500/20 to-pink-500/20',
  },
];

interface FeatureCardProps {
  feature: Feature;
}

const FeatureCard: React.FC<FeatureCardProps> = ({ feature }) => {
  return (
    <div
      className={`group relative p-8 rounded-xl border border-gray-800 hover:border-gray-700 transition-all duration-300 overflow-hidden`}
    >
      <div
        className={`absolute inset-0 bg-gradient-to-br ${feature.gradient} opacity-0 group-hover:opacity-100 transition-opacity duration-300`}
      />

      <div className="relative z-10">
        <div className="flex items-center justify-center w-14 h-14 rounded-lg bg-gradient-to-br from-gray-800 to-gray-900 group-hover:from-gray-700 group-hover:to-gray-800 transition-colors duration-300 mb-6 text-white">
          {feature.icon}
        </div>

        <h3 className="text-xl font-bold text-white mb-3 group-hover:text-gray-50 transition-colors duration-300">
          {feature.title}
        </h3>

        <p className="text-gray-400 text-sm mb-6 group-hover:text-gray-300 transition-colors duration-300">
          {feature.description}
        </p>

        <div className="space-y-2">
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
            Key Benefits
          </p>
          <ul className="space-y-2">
            {feature.benefits.map((benefit, index) => (
              <li
                key={index}
                className="flex items-start gap-2 text-sm text-gray-400 group-hover:text-gray-300 transition-colors duration-300"
              >
                <span className="flex-shrink-0 w-4 h-4 rounded-full bg-gradient-to-r from-blue-500 to-cyan-500 mt-1" />
                <span>{benefit}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="absolute inset-0 border-l border-t border-white/10 rounded-xl pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
    </div>
  );
};

export default function KeyFeaturesShowcaseSection(): React.ReactElement {
  return (
    <section className="relative w-full py-20 px-4 sm:px-6 lg:px-8 bg-black overflow-hidden">
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-blue-500/10 rounded-full filter blur-3xl" />
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full filter blur-3xl" />
      </div>

      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl sm:text-5xl font-bold text-white mb-6">
            Powerful Features for Smarter Cooking
          </h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto">
            Everything you need to revolutionize your meal planning and cooking experience with AI-powered intelligence
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature) => (
            <FeatureCard key={feature.id} feature={feature} />
          ))}
        </div>

        <div className="mt-16 text-center">
          <p className="text-gray-400 mb-6">
            Ready to transform your meal planning?
          </p>
          <button className="inline-flex items-center justify-center px-8 py-3 rounded-lg bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 text-white font-semibold transition-all duration-300 hover:shadow-lg hover:shadow-blue-500/50">
            Get Started Today
          </button>
        </div>
      </div>
    </section>
  );
}