'use client';

import React, { useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import {
  Sparkles,
  Calendar,
  ShoppingCart,
  TrendingUp,
  Settings,
  Zap
} from 'lucide-react';

interface Feature {
  id: number;
  icon: React.ReactNode;
  title: string;
  description: string;
  gradient: string;
  accentColor: string;
}

const KeyProductFeaturesShowcase: React.FC = () => {
  const [visibleFeatures, setVisibleFeatures] = useState<Set<number>>(new Set());
  const refs = useRef<Map<number, HTMLDivElement>>(new Map());

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            const id = parseInt(entry.target.getAttribute('data-id') || '0');
            setVisibleFeatures((prev) => {
              const newSet = new Set(prev);
              newSet.add(id);
              return newSet;
            });
          }
        });
      },
      {
        threshold: 0.1,
        rootMargin: '0px 0px -50px 0px'
      }
    );

    refs.current.forEach((ref) => {
      observer.observe(ref);
    });

    return () => {
      observer.disconnect();
    };
  }, []);

  const features: Feature[] = [
    {
      id: 1,
      icon: <Sparkles className="w-8 h-8" />,
      title: 'AI-Powered Recipes',
      description: 'Get unlimited personalized recipes generated by advanced AI technology tailored to your preferences',
      gradient: 'from-purple-500 to-pink-500',
      accentColor: 'bg-purple-500/20'
    },
    {
      id: 2,
      icon: <Calendar className="w-8 h-8" />,
      title: 'Smart Meal Planning',
      description: 'Intelligent weekly meal plans that adapt to your dietary needs and shopping budget',
      gradient: 'from-blue-500 to-cyan-500',
      accentColor: 'bg-blue-500/20'
    },
    {
      id: 3,
      icon: <ShoppingCart className="w-8 h-8" />,
      title: 'Shopping Lists',
      description: 'Auto-generated shopping lists organized by store section with price optimization',
      gradient: 'from-emerald-500 to-teal-500',
      accentColor: 'bg-emerald-500/20'
    },
    {
      id: 4,
      icon: <TrendingUp className="w-8 h-8" />,
      title: 'Nutrition Tracking',
      description: 'Comprehensive macro and micronutrient tracking for health-conscious cooking',
      gradient: 'from-orange-500 to-red-500',
      accentColor: 'bg-orange-500/20'
    },
    {
      id: 5,
      icon: <Settings className="w-8 h-8" />,
      title: 'Dietary Customization',
      description: 'Full support for allergies, dietary restrictions, and specialized eating plans',
      gradient: 'from-indigo-500 to-purple-500',
      accentColor: 'bg-indigo-500/20'
    },
    {
      id: 6,
      icon: <Zap className="w-8 h-8" />,
      title: 'Quick Prep',
      description: 'Fast recipes with estimated preparation times to fit your busy lifestyle',
      gradient: 'from-yellow-500 to-orange-500',
      accentColor: 'bg-yellow-500/20'
    }
  ];

  return (
    <section className="relative py-20 md:py-32 overflow-hidden bg-gradient-to-b from-slate-50 to-white">
      {/* Background decorative elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-200/30 rounded-full blur-3xl" />
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-blue-200/30 rounded-full blur-3xl" />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            Powerful Features Built for You
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Everything you need to revolutionize your cooking and meal planning experience
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature) => (
            <div
              key={feature.id}
              ref={(el) => {
                if (el) refs.current.set(feature.id, el);
              }}
              data-id={feature.id}
              className="group"
            >
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={
                  visibleFeatures.has(feature.id)
                    ? { opacity: 1, y: 0 }
                    : { opacity: 0, y: 20 }
                }
                transition={{ duration: 0.5, delay: 0.1 * (feature.id - 1) }}
                className="relative h-full rounded-2xl border border-gray-200 bg-white p-8 hover:shadow-2xl hover:border-gray-300 transition-all duration-300"
              >
                {/* Icon Background */}
                <div className={`inline-flex p-4 rounded-xl ${feature.accentColor} mb-6 group-hover:scale-110 transition-transform duration-300`}>
                  <div className={`bg-gradient-to-br ${feature.gradient} bg-clip-text text-transparent`}>
                    {feature.icon}
                  </div>
                </div>

                {/* Content */}
                <h3 className="text-xl font-bold text-gray-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  {feature.description}
                </p>

                {/* Hover Effect Border */}
                <div className={`absolute inset-0 rounded-2xl bg-gradient-to-br ${feature.gradient} opacity-0 group-hover:opacity-5 transition-opacity duration-300 pointer-events-none`} />
              </motion.div>
            </div>
          ))}
        </div>

        {/* CTA Section */}
        <div className="mt-20 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <p className="text-lg text-gray-600 mb-8">
              Start your transformation today with our AI-powered cooking assistant
            </p>
            <button className="inline-flex items-center px-8 py-4 rounded-lg bg-gradient-to-r from-blue-600 to-purple-600 text-white font-semibold hover:shadow-2xl hover:shadow-blue-500/50 transition-all duration-300 transform hover:scale-105">
              Get Started Free
              <Sparkles className="w-5 h-5 ml-2" />
            </button>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default KeyProductFeaturesShowcase;
