'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { Check, Zap, Heart, Clock, TrendingUp, Shield } from 'lucide-react'

interface Feature {
  id: number;
  title: string;
  description: string;
  icon: React.ReactNode;
  gradient: string;
  benefits: string[];
}

const ModernFeaturesSection: React.FC = () => {
  const [hoveredCard, setHoveredCard] = useState<number | null>(null);

  const features: Feature[] = [
    {
      id: 1,
      title: 'AI-Powered Meal Plans',
      description: 'Personalized meal plans generated by advanced AI algorithms tailored to your dietary preferences and health goals.',
      icon: <Zap className="w-8 h-8" />,
      gradient: 'from-emerald-500 to-cyan-500',
      benefits: ['Personalized recommendations', 'Instant generation', 'Adaptive learning'],
    },
    {
      id: 2,
      title: 'Nutritional Tracking',
      description: 'Monitor calories, macros, and micronutrients with precision. Get detailed insights into your daily nutrition.',
      icon: <TrendingUp className="w-8 h-8" />,
      gradient: 'from-cyan-500 to-blue-500',
      benefits: ['Real-time tracking', 'Detailed analytics', 'Goal alignment'],
    },
    {
      id: 3,
      title: 'Meal Customization',
      description: 'Adjust recipes, swap ingredients, and customize portion sizes to match your exact preferences and dietary needs.',
      icon: <Heart className="w-8 h-8" />,
      gradient: 'from-blue-500 to-purple-500',
      benefits: ['Flexible recipes', 'Ingredient swaps', 'Portion control'],
    },
    {
      id: 4,
      title: 'Smart Shopping Lists',
      description: 'Automatically generate optimized shopping lists with ingredient quantities and cost estimates.',
      icon: <Clock className="w-8 h-8" />,
      gradient: 'from-purple-500 to-pink-500',
      benefits: ['Auto-generated lists', 'Cost tracking', 'Bulk savings'],
    },
    {
      id: 5,
      title: 'Health Goal Alignment',
      description: 'Achieve your fitness and wellness objectives with meals specifically designed to support your health targets.',
      icon: <Check className="w-8 h-8" />,
      gradient: 'from-pink-500 to-rose-500',
      benefits: ['Goal-focused meals', 'Progress tracking', 'Expert guidance'],
    },
    {
      id: 6,
      title: 'Food Safety & Quality',
      description: 'Verified recipes with food safety standards and quality ingredients sourced from trusted suppliers.',
      icon: <Shield className="w-8 h-8" />,
      gradient: 'from-rose-500 to-orange-500',
      benefits: ['Safety certified', 'Quality assured', 'Supplier verified'],
    },
  ];

  return (
    <section className="relative w-full py-20 px-4 sm:px-6 lg:px-8 overflow-hidden bg-gradient-to-br from-slate-50 via-slate-50 to-slate-100">
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-emerald-200 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-pulse"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-cyan-200 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-pulse" style={{ animationDelay: '2s' }}></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-blue-200 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-pulse" style={{ animationDelay: '4s' }}></div>
      </div>

      <div className="relative z-10 max-w-7xl mx-auto">
        <div className="text-center mb-16 animate-fade-in">
          <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold mb-6 bg-gradient-to-r from-emerald-600 via-cyan-600 to-blue-600 bg-clip-text text-transparent">
            Powerful Features for Your Journey
          </h2>
          <p className="text-lg sm:text-xl text-slate-600 max-w-2xl mx-auto leading-relaxed">
            Experience the future of meal planning with our comprehensive suite of AI-powered tools designed to transform your eating habits and achieve your health goals effortlessly.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8 mb-16">
          {features.map((feature, index) => (
            <div
              key={feature.id}
              className="group relative h-full"
              onMouseEnter={() => setHoveredCard(feature.id)}
              onMouseLeave={() => setHoveredCard(null)}
              style={{
                animation: `slideUp 0.6s ease-out forwards`,
                animationDelay: `${index * 0.1}s`,
              }}
            >
              <div className="absolute inset-0 bg-gradient-to-br rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300" style={{
                backgroundImage: `linear-gradient(135deg, var(--tw-gradient-stops))`,
              }}></div>

              <div className={`relative h-full p-8 rounded-2xl bg-white border-2 border-slate-200 transition-all duration-300 hover:border-transparent hover:shadow-2xl overflow-hidden`}>
                <div className={`absolute inset-0 bg-gradient-to-br ${feature.gradient} opacity-0 group-hover:opacity-10 transition-opacity duration-300`}></div>

                <div className="relative z-20">
                  <div className={`inline-flex p-3 rounded-xl bg-gradient-to-br ${feature.gradient} text-white mb-6 transition-transform duration-300 group-hover:scale-110 group-hover:-rotate-6`}>
                    {feature.icon}
                  </div>

                  <h3 className="text-xl sm:text-2xl font-bold text-slate-900 mb-3 transition-colors duration-300 group-hover:bg-gradient-to-r group-hover:from-emerald-600 group-hover:to-cyan-600 group-hover:bg-clip-text group-hover:text-transparent">
                    {feature.title}
                  </h3>

                  <p className="text-slate-600 mb-6 leading-relaxed transition-colors duration-300 group-hover:text-slate-700">
                    {feature.description}
                  </p>

                  <div className="space-y-2">
                    {feature.benefits.map((benefit, idx) => (
                      <div key={idx} className="flex items-center gap-2 text-slate-700 transition-all duration-300 group-hover:translate-x-1">
                        <div className={`w-1.5 h-1.5 rounded-full bg-gradient-to-r ${feature.gradient}`}></div>
                        <span className="text-sm font-medium">{benefit}</span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="absolute inset-0 bg-gradient-to-br rounded-2xl opacity-0 group-hover:opacity-5" style={{
                  backgroundImage: `linear-gradient(135deg, var(--tw-gradient-stops))`,
                }}></div>
              </div>
            </div>
          ))}
        </div>

        <div className="flex flex-col sm:flex-row gap-4 justify-center items-center pt-8 border-t border-slate-200 animate-fade-in" style={{ animationDelay: '0.7s' }}>
          <p className="text-slate-600 text-center sm:text-left max-w-lg">
            Ready to revolutionize your meal planning? Start your journey with AI-powered personalized nutrition today.
          </p>
          <Link
            href="/signup"
            className="relative inline-flex items-center justify-center px-8 py-3 font-semibold text-white rounded-xl overflow-hidden group whitespace-nowrap"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-emerald-500 via-cyan-500 to-blue-500 transition-all duration-300 group-hover:shadow-lg group-hover:shadow-cyan-500/50"></div>
            <div className="absolute inset-0 bg-gradient-to-r from-emerald-600 via-cyan-600 to-blue-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            <span className="relative z-10 transition-transform duration-300 group-hover:scale-105">
              Start Free Trial
            </span>
          </Link>
        </div>
      </div>

      <style jsx>{`
        @keyframes slideUp {
          from {
            opacity: 0;
            transform: translateY(30px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        @keyframes fade-in {
          from {
            opacity: 0;
          }
          to {
            opacity: 1;
          }
        }

        .animate-fade-in {
          animation: fade-in 0.6s ease-out forwards;
        }
      `}</style>
    </section>
  );
};

export default ModernFeaturesSection;