'use client';

import { Clock, ChefHat, Flame, Users } from 'lucide-react';

interface Recipe {
  id: number
  name: string
  cuisine: string
  cookingTime: number
  difficulty: 'Easy' | 'Medium' | 'Hard'
  description: string
  servings: number
  gradient: string
  icon: React.ReactNode
}

const recipes: Recipe[] = [
  {
    id: 1,
    name: 'Thai Green Curry',
    cuisine: 'Thai',
    cookingTime: 25,
    difficulty: 'Medium',
    description: 'Aromatic and spicy coconut-based curry with fresh vegetables and basil. AI-optimized for your taste preferences.',
    servings: 4,
    gradient: 'from-green-400 to-emerald-600',
    icon: <ChefHat className="w-8 h-8" />,
  },
  {
    id: 2,
    name: 'Margherita Pasta',
    cuisine: 'Italian',
    cookingTime: 20,
    difficulty: 'Easy',
    description: 'Classic pasta with fresh tomatoes, basil, and creamy mozzarella. Perfect for quick weeknight dinners.',
    servings: 2,
    gradient: 'from-red-400 to-pink-600',
    icon: <Flame className="w-8 h-8" />,
  },
  {
    id: 3,
    name: 'Beef Tacos',
    cuisine: 'Mexican',
    cookingTime: 30,
    difficulty: 'Easy',
    description: 'Seasoned ground beef with fresh toppings and warm tortillas. Customizable for any dietary preference.',
    servings: 4,
    gradient: 'from-yellow-400 to-orange-600',
    icon: <ChefHat className="w-8 h-8" />,
  },
  {
    id: 4,
    name: 'Sushi Rolls',
    cuisine: 'Japanese',
    cookingTime: 40,
    difficulty: 'Hard',
    description: 'Delicate rolls with fresh fish, vegetables, and perfectly seasoned rice. Step-by-step AI guidance included.',
    servings: 4,
    gradient: 'from-blue-400 to-cyan-600',
    icon: <Flame className="w-8 h-8" />,
  },
  {
    id: 5,
    name: 'Coq au Vin',
    cuisine: 'French',
    cookingTime: 90,
    difficulty: 'Hard',
    description: 'Tender chicken braised in rich red wine sauce with mushrooms and pearl onions. Restaurant-quality at home.',
    servings: 6,
    gradient: 'from-purple-400 to-indigo-600',
    icon: <ChefHat className="w-8 h-8" />,
  },
  {
    id: 6,
    name: 'Pad Thai',
    cuisine: 'Thai',
    cookingTime: 15,
    difficulty: 'Medium',
    description: 'Stir-fried noodles with shrimp, peanuts, and lime in a savory sweet sauce. Ready in under 20 minutes.',
    servings: 2,
    gradient: 'from-amber-400 to-yellow-600',
    icon: <Flame className="w-8 h-8" />,
  },
]

const getDifficultyColor = (difficulty: string): string => {
  switch (difficulty) {
    case 'Easy':
      return 'bg-green-100 text-green-800'
    case 'Medium':
      return 'bg-yellow-100 text-yellow-800'
    case 'Hard':
      return 'bg-red-100 text-red-800'
    default:
      return 'bg-gray-100 text-gray-800'
  }
}

export default function SampleRecipes(): React.ReactElement {
  return (
    <section className="w-full py-16 px-4 bg-gradient-to-b from-slate-50 to-white">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-gray-900 mb-4">
            AI-Generated Recipes Tailored to You
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Explore delicious recipes generated by our advanced AI. Each recipe includes cooking times, difficulty levels, nutrition info, and step-by-step instructions. Get unlimited personalized recipes based on your taste, dietary needs, and available ingredients.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {recipes.map((recipe) => (
            <div
              key={recipe.id}
              className="group relative bg-white rounded-2xl overflow-hidden shadow-lg hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-2 cursor-pointer"
            >
              <div
                className={`absolute inset-0 bg-gradient-to-br ${recipe.gradient} opacity-0 group-hover:opacity-10 transition-opacity duration-300`}
              />

              <div className={`h-32 bg-gradient-to-br ${recipe.gradient} flex items-center justify-center relative overflow-hidden`}>
                <div className="absolute inset-0 opacity-20">
                  <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white to-transparent animate-pulse" />
                </div>
                <div className="text-white relative z-10">
                  {recipe.icon}
                </div>
              </div>

              <div className="p-6 relative z-10">
                <div className="mb-3">
                  <h3 className="text-xl font-bold text-gray-900 mb-1 group-hover:text-transparent group-hover:bg-gradient-to-r group-hover:from-gray-900 group-hover:to-gray-600 group-hover:bg-clip-text transition-all">
                    {recipe.name}
                  </h3>
                  <p className="text-sm font-medium text-gray-500 uppercase tracking-wide">
                    {recipe.cuisine}
                  </p>
                </div>

                <p className="text-gray-600 text-sm mb-4 line-clamp-2">
                  {recipe.description}
                </p>

                <div className="flex flex-wrap gap-2 mb-4">
                  <span className={`inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-semibold ${getDifficultyColor(recipe.difficulty)}`}>
                    <Flame className="w-3 h-3" />
                    {recipe.difficulty}
                  </span>
                </div>

                <div className="space-y-2 border-t border-gray-100 pt-4">
                  <div className="flex items-center justify-between text-sm">
                    <div className="flex items-center gap-2 text-gray-600">
                      <Clock className="w-4 h-4" />
                      <span>{recipe.cookingTime} mins</span>
                    </div>
                    <div className="flex items-center gap-2 text-gray-600">
                      <Users className="w-4 h-4" />
                      <span>Serves {recipe.servings}</span>
                    </div>
                  </div>
                </div>

                <button className="w-full mt-4 px-4 py-2 bg-gradient-to-r from-gray-900 to-gray-700 text-white font-semibold rounded-lg hover:from-gray-800 hover:to-gray-600 transition-all duration-200 transform group-hover:scale-105">
                  View Recipe
                </button>
              </div>

              <div className="absolute inset-0 border-2 border-transparent group-hover:border-gray-200 rounded-2xl transition-colors duration-300" />
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}